use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Represents the response containing authentication tokens.
///
/// Contains both a long-lived token and a short-lived token.
/// The `long_token` is only returned during login or registration.
#[derive(Debug, Serialize, Deserialize, ToSchema)]
pub struct TokenResponse {
    /// ## Long token
    ///
    /// The long token is stored in the local storage and in the database.  
    /// This token is used to authenticate the user and generate the short token.  
    /// It is **only** present in the response when the user logs in or registers.
    #[schema(
        example = "<the token>",
        nullable = true
    )]
    pub long_token: Option<String>,

    /// ## Short token
    ///
    /// The short token is also stored in local storage, but not in the database.  
    /// It is used to authenticate the user in microservices and is valid for a short period of time.  
    /// It is generated by the long token and signed with a secret key, which is shared among microservices for verification.
    #[schema(example = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.shorttoken...")]
    pub short_token: String,
}
